[package]
name = "tree_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
nestify = "0.3.3"
quote = "1.0.37"
struct_iterable = "0.1.1"
syn = {version = "2.0.79", features = ["full", "extra-traits"]}

#[lib]
#proc-macro = true





